export const profile = {
  name: "Akhyar",
  alternateName: "Yar",
  jobTitle: "Software Engineer",
  location: "Banda Aceh, Indonesia",
  email: "ahyar12324@gmail.com",
  phone: "(+62) 822-7533-1698",
  siteUrl: "https://akhyar.dev",
  socials: {
    github: "https://github.com/Akhyarrrrr",
    linkedin: "https://www.linkedin.com/in/akhyarrr/",
    instagram: "https://instagram.com/akhyaar._",
  },
  skills: [
    "TypeScript",
    "JavaScript",
    "PHP",
    "Kotlin",
    "Python",
    "React",
    "Next.js",
    "Node.js",
    "Express.js",
    "React Native",
    "Expo",
    "Laravel",
    "WordPress",
    "REST API",
    "Tailwind CSS",
    "PostgreSQL",
    "MySQL",
    "Supabase",
    "Docker",
    "AWS EC2",
    "GCP",
    "Git",
  ],
} as const;
